---
title: "cake_analysis"
output: html_document
date: "2023-04-13"
---

```{r}
library(tidyverse)
library(here)
```

Cake data was
lots of NAS
All in wide format
not clean names



Read in data
```{r}
cake_clean <- read_csv(here("raw_data/cake_clean.csv"))
```

Q1: Which cake has the most cocoa in it?
Answer: One bowl chocolate with 10 tablespoons
```{r}
cake_clean %>% 
  filter(ingredient == "Cocoa") %>% 
  arrange(desc(amount))
```

Q2: For sponge cake, how many cups of ingredients are used in total?
Answer: 9.25 cups
```{r}
cake_clean %>% 
  filter(Cake == "Sponge") %>% 
  summarise(total_cups = sum(amount))
```

Q3: How many ingredients are measured in teaspoons?

```{r}
cake_clean %>%
  select(ingredient, measure) %>% 
  filter(measure == "teaspoon") %>% 
  count()
  
```


Q4: Which cake has the most unique ingredients?

```{r}
cake_clean %>% 
  group_by(Cake) %>%
  summarise(number_of_ingredients = n_distinct(ingredient)) %>% 
  slice_max(number_of_ingredients, n = 1)
  
```




Q5: Which ingredients are used only once?
